language: java
sudo: false
env:
  global:
  - secure: H8KmGcatFptSW5Mvbplqa3vtTvDwIPzMhwu4FNZbNmr8zc+8NFN1Lgw5YP4sdL86BQoAerQ8hrhRMH5xfPjLJdtIjGBKqPrRIxmu+X9zWwuat7S4x5P3R0HAR4LrhAVPcnWhimfgyOJQF98ko51ipnCnkI5ZVf7BKd9MvfutFgc=
notifications:
  email: false
script:
- mvn clean install
deploy:
  provider: releases
  api-key: "${GITHUB_TOKEN}"
  file:
  - target/HolographicScoreboard.jar
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
cache:
  directories:
  - "$HOME/.m2"
